### ISSUE TITLE
Default zenity heights and widths are sometimes ridiculous

### ISSUE THREAD

**Issue by bertvandepoel** [clue/php-zenity-react#40]
When using long messages in InfoDialog, zenity yield a very very high dialog with a huge amount of white spacing. This is because zenity itself can't seem to calculate default height and width very well with text that spans many lines and especially when it contains newlines.

For example:

``` php
$info = new InfoDialog('You chose to cancel the synchronisation. No information was synchronised. What does this mean? Your records will not be available to other toughbooks, on the label print screen or anywhere in the depot system. You will also not receive any records from other toughbooks or the server. Be sure to resolve any problems soon so you can sync again.');
$launcher->waitFor($info);
```

The problem is even bigger with listRadio as Zenity then decides to make the windows far too small, hiding some of the radio options. 

For example: 

``` php
$conflicttext = "There is a conflict between your data and that of the server. A new record you created already exists on the server. \n\nInvolved table: tbl_excavation \nNames of columns: id, excavation, year, site, locus_system, active, create_time, create_username, update_time, update_username, sync_time
Record on your toughbook: XX-2016-XXXX, XX, 2016, XXXX, 1, 1, 2016-06-08 00:12:49.917372+03, we.lovelongnamesandstuff, 2016-06-08 00:12:49.917372+03, some.name, \nRecord on the server: XX-2016-XXXX, XX, 2016, XXXX, 1, 1, 2016-06-08 00:12:49.917372+03, we.lovelongnamesandstuff, 2016-06-08 00:12:49.917372+03, some.name, \n\nWhat should be done to resolve this conflict?";

$resolution = $launcher->waitFor($builder->listRadio(array('tb' => 'Overwrite the server, the record on my toughbook is correct', 'serv' => 'The record on the server is correct, overwrite the record on my toughbook', 'cancel' => 'I don\'t know, please cancel the synchronisation (new finds will NOT be available on the server)'), $conflicttext, 'cancel'));
```

I am not sure this is a problem with every version of the Zenity binary but it certainly is on 3.8.0. If it turns out to be a problem on our production devices I will look into writing a patch for the --height and --width options of the Zenity binary and you'll get a PR of course.

**Comment by clue** [comment]
Thanks for posting this issue and letting us know :+1: 

I'm sure this is something many people will be interested in, but I'm currently undecided if this is actually something we should handle in this library.

This library aims to be very thing wrapper around the Zenity binary and if it doesn't doesn't get handled in he underlying binary, I'm not sure we should (try to) do so here.

Perhaps we can add some documentation and possibly some means to work around this if this is desired (such as a helper method etc.)?

**Comment by bertvandepoel** [comment]
I think you have misunderstood. The binary supports --width and --height, it is the php-zenity-react library that does not support it. We're not going to patch upstream at gnome of course :stuck_out_tongue_winking_eye:

**Comment by clue** [comment]
`InfoDialog` extends `AbstractMessageDialog` which extends `AbstractTextDialog` which extends `AbstractDialog` which provides a `setWidth()` and a `setHeight()` method. Does this help? :)

**Comment by bertvandepoel** [comment]
Weird, for some reason my IDE didn't tell me I had access to those functions and I totally missed them in the code. Silly me. I'll see whether it fixes things. Thx :D 

PS: I've sent you a tweet about another weird issue I have, do you prefer I file an issue or tweet you when I'm not sure it's bug/missing feature or just something I missed?

**Comment by clue** [comment]
> I'll see whether it fixes things.

Let me know if this worked out or if there's something that needs to be done here :)

> PS: I've sent you a tweet about another weird issue I have, do you prefer I file an issue or tweet you when I'm not sure it's bug/missing feature or just something I missed?

There's a fair chance this means the docs aren't quite ideal, in that case we should keep track of this here so we can improve this :+1:

**Comment by clue** [comment]
Original:
![bildschirmfoto_2016-12-02_11-01-25](https://cloud.githubusercontent.com/assets/776829/20829951/b0458ccc-b87e-11e6-8bbb-9994773ab6ee.png)

After applying `setWidth(400)`:
![bildschirmfoto_2016-12-02_11-02-06](https://cloud.githubusercontent.com/assets/776829/20829974/c89131d2-b87e-11e6-9bf4-40171f5e30d8.png)

I assume the above may have resolved this, so I'm closing this due to a lack of feedback. Please report back if this problem persists :+1:
