### ISSUE TITLE
How to catch close by user

### ISSUE THREAD

**Issue by bertvandepoel** [clue/php-zenity-react#43]
QuestionDialog returns false when a user closes the window instead of pressing yes or no. Same for listRadio when the close button is pressed instead of one of the options.

However, I'm trying to check whether a user has closed an asynchronously started progress bar and I can't seem to find anything in place to check that. 

After examining further I have found that the most convenient way to check, is to var_export the zen object and then check whether the process is still running or not. But this seems like either a missing feature or something that I haven't been able to spot in the docs and code.

Any pointers or is this really just missing?

**Comment by clue** [comment]
All dialogs should reject with a boolean `false` if the user cancels the dialog.

I've just verified the progress-pulsate.php example does just this: https://github.com/clue/php-zenity-react/blob/d3a64dd245dbea386757add993a624609388e5b4/examples/progress-pulsate.php#L46

Does this help?

**Comment by clue** [comment]
I assume the above may have resolved this, so I'm closing this due to a lack of feedback. Please report back if this problem persists :+1:
